### ISSUE TITLE
Fuller data article: missing fn 69

### ISSUE THREAD

**Issue by djvill** [sx-archipelagos/sxa#53]
Footnote 69 callout [present in main text](https://github.com/archipelagosjournal/archipelagos/blob/f73351a22ade984c0ab940f2e18133474de63897/_issue06/fuller-data.md?plain=1#L91), but no footnote text exists

**Comment by Denubis** [comment]
@elotroalex looks like a migration-to-markdown issue. The footnote isn't present in the footnotes list.

**Comment by elotroalex** [comment]
I'll write to Nicté to see if she has the original. Thanks, @djvill

**Comment by elotroalex** [comment]
Fixed! Author says that she can't find a note for that one. I didn't press her. Just silently deleted the broken anchor.
